site_name: Electrical Engineering Toolbox
site_url: https://jeonmaxx.github.io/ElectricalEngineeringDocumentation
nav: 
- Home: index.md
- Widerstand: resistance.md
- Leiterbahnbreiten: traceWidths.md
theme:
    name: mkdocs
    locale: de
